# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
 ignore:
      # WARNING: Kotlin > 2.2.30 incompatible with CodeQL
      # To be updated when CodeQL supports Kotlin 2.3+
      # Issue: https://github.com/github/codeql/issues/XXXXX
      # Expected re-evaluation date: 2026-04-01
      # TEMPORARILY ignore Kotlin 2.3.x
      - dependency-name: "org.jetbrains.kotlin:*"
        versions: ["2.3.x"] 
        until: 2026-04-01
      
