name: Android CI
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore keystore
        run: |
          if [ -n "${{ secrets.KEYSTORE_FILE }}" ]; then
            echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > app/keystore.jks
          fi

      - name: Export signing env variables
        run: |
          echo "KEYSTORE_FILE=keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Bundle Release
        run: ./gradlew bundleRelease
