name: Android CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   # adapte selon ta version

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Restore keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Assemble Release
        run: ./gradlew assembleRelease

      - name: Bundle Release
        run: ./gradlew bundleRelease
