name: Deploy to Internal Testing
permissions:
  contents: read
  pull-requests: write

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - release

env:
  GRADLE_BUILD_ACTION_CACHE_KEY: v1-gradle-cache

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Increment versionCode
        id: version
        run: |
          # Extract current versionCode from build.gradle.kts
          CURRENT_VERSION_CODE=$(grep -o 'versionCode [0-9]*' app/build.gradle.kts | awk '{print $2}')
          echo "Current versionCode: $CURRENT_VERSION_CODE"
          
          # Increment versionCode
          NEW_VERSION_CODE=$((CURRENT_VERSION_CODE + 1))
          echo "New versionCode: $NEW_VERSION_CODE"
          
          # Update build.gradle.kts with new versionCode
          sed -i "s/versionCode $CURRENT_VERSION_CODE/versionCode $NEW_VERSION_CODE/" app/build.gradle.kts
          
          # Set outputs for later steps
          echo "new_version_code=$NEW_VERSION_CODE" >> $GITHUB_OUTPUT
          echo "NEW_VERSION_CODE=$NEW_VERSION_CODE" >> $GITHUB_ENV

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build Android App Bundle
        run: |
          ./gradlew :app:bundleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 7

      - name: Commit versionCode increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app/build.gradle.kts
          git commit -m "ci: increment versionCode to $NEW_VERSION_CODE"
          git push

      - name: Upload to Play Store (Internal Test)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          packageName: com.yourcompany.yourapp
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal

          status: completed
